name: flutter_ble_peripheral
description: This plugin enables a device to be set into peripheral mode, and advertise custom
  services and characteristics.
version: 0.5.0+1
homepage: https://github.com/juliansteenbakker/flutter_ble_peripheral

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter_lints: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.flutter_ble_peripheral
        pluginClass: FlutterBlePeripheralPlugin
      ios:
        pluginClass: FlutterBlePeripheralPlugin
      macos:
        pluginClass: FlutterBlePeripheralPlugin
